### ISSUE TITLE
New to Github... how do I download the compiled ZIP

### ISSUE THREAD

**Issue by SRobbins1977** [DNNCommunity/DNN.Wiki#1]
I'm kind of new to Github.  On codeplex, you could just download the compiled ZIP on the front page.  But i'm not sure where to DL it here on github. How do I download the compiled ZIP?

**Comment by jbrinkman** [comment]
If you go to the Project Home page, you will see a link at the top to the [Releases](https://github.com/DNNCommunity/DNN.Wiki/releases) page. This contains the releases for the project.

**Comment by SRobbins1977** [comment]
Thanks Joe.
