### ISSUE TITLE
how to instal

### ISSUE THREAD

**Issue by omidit2019** [DNNCommunity/DNN.Wiki#23]
hi 
there is no install file in files
how i can instal wiki in dnn 9
tnx

**Comment by WillStrohl** [comment]
Download the package(s) from the link below.  

[Latest Release of the DNN Wiki Module](https://github.com/DNNCommunity/DNN.Wiki/releases/latest)  

Watch this video to learn what to do with it.  

[How to install or upgrade a module in DNN](https://www.youtube.com/watch?v=MgLaV0J_eLk)
